### ISSUE TITLE
[Enhancement] BeEqual("") -> BeEmpty()

### ISSUE THREAD

**Issue by pohly** [nunnatsa/ginkgolinter#108]
**Is your feature request related to a problem? Please describe.**

Instead of `BeEqual("")` it would be better to use `BeEmpty()`. It supports strings and makes the intent and failure message clearer.

**Additional context**

https://github.com/kubernetes/kubernetes/pull/120403#pullrequestreview-1623915358

**Comment by pohly** [comment]
I've not checked whether this is already supported - at least the version in the latest golangci-lint doesn't seem to have it.

**Comment by nunnatsa** [comment]
Hi @pohly, thanks for this idea. I think many developers will find go  Equal("") better readable than BeEmpty().

It like in a regular go condition, that many developers prefer 

if s == "" 

Over 

if len(s) == 0

**Comment by pohly** [comment]
Yes, let's do that.

**Comment by pohly** [comment]
This is too contentious, let's not do this.
